title: Data Warehouse Direct Access User Guide
description: Connecting to the Data Warehouse without a browser.
theme: just-the-docs

url: https://bikerben33.github.io/DWDirectAccessUGMD/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
